Add .pylintrc and run pylint checks in CI workflow.
PiperOrigin-RevId: 364342400

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -24,18 +24,26 @@ jobs:
       - name: Install dependencies
         run: |
           set -xe
-          python -m pip install --upgrade pip setuptools wheel
-          python -m pip install flake8 pytest-xdist pytype
-          python -m pip install -r requirements/requirements.txt
-          python -m pip install -r requirements/requirements-test.txt
+          pip install --upgrade pip setuptools wheel
+          pip install flake8 pytest-xdist pytype pylint pylint-exit
+          pip install -r requirements/requirements.txt
+          pip install -r requirements/requirements-test.txt
         shell: bash
       - name: Lint with flake8
         run: |
           set -xe
-          # stop the build if there are Python syntax errors or undefined names
-          cd optax
-          flake8 `find -name '*.py' | xargs` --count --select=E9,F63,F7,F82,E225,E251 --show-source --statistics
-          cd ..
+          flake8 `find optax -name '*.py' | xargs` --count --select=E9,F63,F7,F82,E225,E251 --show-source --statistics
+      - name: Lint with pylint
+        run: |
+          set -xe
+          # Fail on errors, warning, conventions and refactoring messages.
+          PYLINT_ARGS="-efail -wfail -cfail -rfail"
+
+          # Lint modules and tests separately.
+          pylint --rcfile=.pylintrc `find optax -name '*.py' | grep -v 'test.py' | xargs` || pylint-exit $PYLINT_ARGS $?
+
+          # Disable `protected-access` warnings for tests.
+          pylint --rcfile=.pylintrc `find optax -name '*_test.py' | xargs` -d W0212 || pylint-exit $PYLINT_ARGS $?
       - name: Build
         run: |
           set -xe
